version: '3'

services:
  server:
    build: ./server
    expose:
      - "5000"
    environment:
      PORT: "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/usr/app/server/src
    command: npm run start
  client:
    build: ./client
    expose:
      - "3000"
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/app/client/src
      - ./client/public:/usr/app/client/public
    links:
      - server
    command: npm run start
